site_name: Data Studio
repo_url: https://github.com/jsoma/data-studio
repo_name: jsoma/data-studio
edit_uri: edit/master/docs/
copyright: Copyright &copy; 2022 Jonathan Soma
nav:
  - Home: index.md
  - Writing/Stories:
    - Generating ideas: writing/ideas.md
    - Pacing and Managing Risk: writing/pacing.md
    - File formats: writing/file-formats.md
  - Data:
    - Reshaping long data to wide: reshaping/long-to-wide.ipynb
    - Reshaping wide data to long (tidy): reshaping/wide-to-long.ipynb
    - Transposing data: reshaping/transposing-data.ipynb
  - Graphs:
    - graphs.md
    - Plotnine flipbook: graphs/plotnine-flipbook.ipynb
  - Maps: maps.md
  - Web:
    - sites.md
    - web/basic-article-page.md
    - web/linking-between-folders.md
    - web/organizing-styles-and-stylesheets.md
  - Apps: apps.md
  - How They Did It: examples.md
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: UA-5541738-17
theme:
  name: material
  custom_dir: material_custom
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: jsoma
      repo: data-studio-book
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - mkdocs-jupyter:
      include_source: True
